Controllers/POIController.cs
using Microsoft.AspNetCore.Mvc;
using Digitalnamapa.Models;
using Microsoft.Extensions.Localization;

namespace Digitalnamapa.Controllers
{
    public class POIController : Controller
    {
        private readonly ILogger<POIController> _logger;
        private readonly IStringLocalizer<SharedResource> _localizer;

        public POIController(ILogger<POIController> logger, IStringLocalizer<SharedResource> localizer)
        {
            _logger = logger;
            _localizer = localizer;
        }

        // GET: POI
        public IActionResult Index()
        {
            return View();
        }



        // GET: POI/Details/5
        public IActionResult Details(int id)
        {
            // Za sada vraćamo hardkodirane podatke za Carsku palatu (id=1)
            if (id == 1)
            {
                var palata = new PointOfInterest
                {
                    Id = 1,
                    Name = _localizer["Popup_ImperialPalace_Title"],
                    Description = _localizer["Popup_ImperialPalace_Description"],
                    FullDescription = _localizer["Details_ImperialPalace_FullDescription"],
                    Latitude = 44.966733731689764,
                    Longitude = 19.610175926337753,
                    Type = PointType.Dešavanja,
                    Icon = "/images/palata.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_Parade"],
                            Date = new DateTime(2025, 8, 1), // Prvi dan, ali opis i vreme pokrivaju oba datuma
                            Time = "01.08. i 02.08. 2025. u 20:00h",
                            Description = _localizer["Event_ParadeDesc"]
                        }
                    }
                };
                return View(palata);
            }
            else if (id == 2)
            {
                var gradskiPark = new PointOfInterest
                {
                    Id = 2,
                    Name = _localizer["Popup_CityPark_Title"],
                    Description = _localizer["Popup_CityPark_Description"],
                    FullDescription = _localizer["Details_CityPark_FullDescription"],
                    Latitude = 44.96772509437982,
                    Longitude = 19.608036819991597,
                    Type = PointType.Dešavanja,
                    Icon = "/images/park.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_ExperimentalArchaeology"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "10:00-19:00",
                            Description = _localizer["Event_ExperimentalArchaeology"]
                        },
                        new Event
                        {
                            Id = 2,
                            Title = _localizer["Event_RomanBazaar"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "10:00-19:00",
                            Description = _localizer["Event_RomanBazaar"]
                        },
                        new Event
                        {
                            Id = 3,
                            Title = _localizer["Event_CaptureRomanMoment"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "12h-19h",
                            Description = _localizer["Event_CaptureRomanMomentOrganizer"]
                        }
                    }
                };
                return View(gradskiPark);
            }
            else if (id == 13)
            {
                var bazilika = new PointOfInterest
                {
                    Id = 13,
                    Name = _localizer["Popup_Basilica_Title"],
                    Description = _localizer["Popup_Basilica_Description"],
                    FullDescription = _localizer["Details_Basilica_FullDescription"],
                    Latitude = 44.969564113652375,
                    Longitude = 19.60932520307554,
                    Type = PointType.Dešavanja,
                    Icon = "/images/bazilika.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_OpenForVisitorsDuring"],
                            Date = new DateTime(2025, 8, 1),
                            Time = "tokom festivala",
                            Description = _localizer["Event_OpenForVisitorsDuring"]
                        }
                    }
                };
                return View(bazilika);
            }
            else if (id == 4)
            {
                var lapidarijum = new PointOfInterest
                {
                    Id = 4,
                    Name = _localizer["Popup_Lapidarium_Title"],
                    Description = _localizer["Popup_Lapidarium_Description"],
                    FullDescription = _localizer["Details_SremMuseum_FullDescription"],
                    Latitude = 44.96747443960462,
                    Longitude = 19.60618380441317,
                    Type = PointType.Dešavanja,
                    Icon = "/images/lapidarijum.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_ExperimentalArchaeology"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "10h-19h",
                            Description = _localizer["Event_ExperimentalArchaeology"]
                        }
                    }
                };
                return View(lapidarijum);
            }
            else if (id == 9)
            {
                var galerija = new PointOfInterest
                {
                    Id = 9,
                    Name = _localizer["Popup_Gallery_Title"],
                    Description = _localizer["Popup_Gallery_Description"],
                    FullDescription = _localizer["Details_Gallery_FullDescription"],
                    Latitude = 44.9675542153864,
                    Longitude = 19.607229753180945,
                    Type = PointType.Dešavanja,
                    Icon = "/images/galerija.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_OpenForVisitors"],
                            Date = new DateTime(2025, 8, 1),
                            Time = "tokom festivala",
                            Description = _localizer["Event_OpenForVisitors"]
                        }
                    }
                };
                return View(galerija);
            }
            else if (id == 8)
            {
                var pozoriste = new PointOfInterest
                {
                    Id = 8,
                    Name = _localizer["Popup_Theatre_Title"],
                    Description = _localizer["Popup_Theatre_Description"],
                    FullDescription = _localizer["Details_Theatre_FullDescription"],
                    Latitude = 44.967912043904136,
                    Longitude = 19.607416066846497,
                    Type = PointType.Dešavanja,
                    Icon = "/images/pozoriste.png",
                    IsActive = true,
                    Events = new List<Event>()
                };
                return View(pozoriste);
            }
            else if (id == 6)
            {
                var biblioteka = new PointOfInterest
                {
                    Id = 6,
                    Name = _localizer["Popup_Library_Title"],
                    Description = _localizer["Popup_Library_Description"],
                    FullDescription = _localizer["Details_Library_FullDescription"],
                    Latitude = 44.96812210658803,
                    Longitude = 19.607509922876687,
                    Type = PointType.Dešavanja,
                    Icon = "/images/biblioteka.png",
                    IsActive = true,
                    Events = new List<Event>
                    {
                        new Event
                        {
                            Id = 1,
                            Title = _localizer["Event_DigitalInteraction"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "10h-19h",
                            Description = _localizer["Event_DigitalInteraction"]
                        },
                        new Event
                        {
                            Id = 2,
                            Title = _localizer["Event_ChildrenWorkshopWriting"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "10:00-11:30",
                            Description = _localizer["Event_ChildrenWorkshopWritingModerators"]
                        },
                        new Event
                        {
                            Id = 3,
                            Title = _localizer["Event_ChildrenWorkshopPattern"],
                            Date = new DateTime(2025, 8, 2),
                            Time = "12:00-13:30",
                            Description = _localizer["Event_ChildrenWorkshopPatternModerators"]

Views/Shared/_Layout.Layout.cshtml
    <header class="border-bottom">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
 

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<!DOCTYPE html>
<html lang="@System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - @Localizer["SiteTitle"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/map.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Digitalnamapa.styles.css" asp-append-version="true" />
    <!-- Google Fonts - Amatic SC, Marcellus, Open Sans -->
    <link href="https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Marcellus&family=Open+Sans:ital,wght@0,300;0,400;0,600;0,700;1,400&display=swap" rel="stylesheet">
    <!-- Leaflet CSS -->
    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin=""/>
</head>
<body>


    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="POI" asp-action="Map">@Localizer["SiteTitle"]</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="POI" asp-action="Map">@Localizer["Navigation_Map"]</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="POI" asp-action="Program">@Localizer["Navigation_Program"]</a>
                        </li>
                    </ul>
                    <!-- Language Switcher -->
                    <ul class="navbar-nav">
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="languageDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                @(System.Globalization.CultureInfo.CurrentUICulture.TwoLetterISOLanguageName.ToUpper())
                            </a>
                            <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="languageDropdown">
                                <li>
                                    <form asp-controller="Home" asp-action="SetLanguage" method="post" style="display: inline;" onsubmit="console.log('Submitting Serbian form');">
                                        <input type="hidden" name="culture" value="sr" />
                                        <input type="hidden" name="returnUrl" value="@Context.Request.Path@Context.Request.QueryString" />
                                        <button type="submit" class="dropdown-item">🇷🇸 Srpski</button>
                                    </form>
                                </li>
                                <li>
                                    <form asp-controller="Home" asp-action="SetLanguage" method="post" style="display: inline;" onsubmit="console.log('Submitting English form');">
                                        <input type="hidden" name="culture" value="en" />
                                        <input type="hidden" name="returnUrl" value="@Context.Request.Path@Context.Request.QueryString" />
                                        <button type="submit" class="dropdown-item">🇬🇧 English</button>
                                    </form>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main role="main">
            @RenderBody()
        </main>

    <footer class="footer">      
            &copy; 2025 - @Localizer["SiteTitle"]

    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Leaflet JS -->
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>

    <!-- Custom JS for map -->
    <script src="~/js/mapa.js?v=20240726BETA" type="text/javascript"></script>



    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>